name: Sync Labels
on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - opened
      - labeled

# Declare default permissions as read only.
permissions: read-all

jobs:
  labels:
    # yamllint disable-line rule:line-length
    uses: outoforbitdev/reusable-workflows-library/.github/workflows/label-manager.yml@6d3deb76a8bc67b0c56bfae3e58d9b9566a967d0 # v1.3.0
    permissions:
      issues: write
